################################################
#               Variable header                #
################################################

define OWNAS = 4242423152;
define OWNIP = 172.22.129.65;
define OWNIPv6 = fdb2:e864:673e:3152::65;

define OWN_NETS = [172.22.129.64/26+];
define OWN_NETS_V6 = [fdb2:e864:673e::/48+];

define IBGP_NETS_4 = [172.22.129.64/26+, 172.22.129.73/32, 172.22.129.74/32, 172.22.129.75/32];
define IBGP_NETS_6 = [fdb2:e864:673e::/48+, fdb2:e864:673e::53/128, fdb2:e864:673e::5353/128, fdb2:e864:673e::1/128];

define DN42_REGION = 41;
define DN42_COUNTRY = 1826;

################################################

hostname "rt0.test.tatk.network";

router id OWNIP;

protocol device {
    scan time 10;
}

log syslog all;

################################################
#              Utility Functions               #
################################################

function is_self_net() {
  return net ~ OWN_NETS;
}

function is_self_net_v6() {
  return net ~ OWN_NETS_V6;
}

function is_self_net_aggregate() {
  return net ~ [
    172.22.129.64/26
  ] || net ~ [
    fdb2:e864:673e::/48
  ];
}

function is_valid_network() {
  return net ~ [
    172.20.0.0/14{21,29}, # dn42
    172.20.0.0/24{28,32}, # dn42 Anycast
    172.21.0.0/24{28,32}, # dn42 Anycast
    172.22.0.0/24{28,32}, # dn42 Anycast
    172.23.0.0/24{28,32}, # dn42 Anycast
    172.31.0.0/16+,       # ChaosVPN
    10.100.0.0/14+,       # ChaosVPN
    10.127.0.0/16{16,32}, # neonetwork
    10.0.0.0/8{15,24}     # Freifunk.net
  ];
}

function is_valid_network_v6() {
  return net ~ [
    fd00::/8{44,64} # ULA address space as per RFC 4193
  ];
}

function is_ibgp_network() {
    if net.type = NET_IP4 && net ~ IBGP_NETS_4 then {
        return true;
    } else if net.type = NET_IP6 && net ~ IBGP_NETS_6 then {
        return true;
    } else {
        return false;
    }
}

################################################
#               Kernel Routes                  #
################################################

protocol kernel {
    scan time 20;

    ipv6 {
        import none;
        export filter {
            if source = RTS_STATIC then reject;
            krt_prefsrc = OWNIPv6;
            accept;
        };
    };
};

protocol kernel {
    scan time 20;

    ipv4 {
        import none;
        export filter {
            if source = RTS_STATIC then reject;
            krt_prefsrc = OWNIP;
            accept;
        };
    };
}

################################################
#               Static Routes                  #
################################################

protocol static {
        route 172.22.129.64/26 reject;

        route 172.20.0.0/14 reject;
        route 172.31.0.0/16 reject;
        route 10.100.0.0/14 reject;
        route 10.0.0.0/8 reject;
        route 10.127.0.0/16 reject;

    ipv4 {
        import all;
        export none;
    };
}

protocol static {
        route fdb2:e864:673e::/48 reject;

        route fd00::/8 reject;
        route fd10:127::/32 reject;

    ipv6 {
        import all;
        export none;
    };
}

################################################
#                  Includes                    #
################################################

include "/etc/bird/dn42-functions.conf";
include "/etc/bird/templates.conf";
include "/etc/bird/filters.conf";
include "/etc/bird/peers.conf";
include "/peers/*.conf";