################################################
#                Default DN42                  #
################################################

function dn42_import_filter(int link_latency; int link_bandwidth; int link_crypto) {
    if net.type = NET_IP4 && is_valid_network() && !is_self_net() then {


    } else if net.type = NET_IP6 && is_valid_network_v6() && !is_self_net_v6() then {


    } else {
        reject "Unknown net type?! ", net;
    }

    update_flags(link_latency, link_bandwidth, link_crypto);

    accept;
}

function dn42_export_filter(int link_latency; int link_bandwidth; int link_crypto) {
    if ((is_valid_network() || is_valid_network_v6()) && source ~ [RTS_STATIC, RTS_BGP, RTS_DEVICE]) then {

        if source ~ [RTS_STATIC, RTS_DEVICE] then {
            # Do not export static routes that are more specifics of OWNNETS(6)
            if ((is_self_net() || is_self_net_v6()) && !is_self_net_aggregate()) then {
                reject;
            }

            bgp_community.add((64511, DN42_REGION));
        }

        if (link_latency > 0 && link_bandwidth > 0 && link_crypto > 0) then {
            update_flags(link_latency, link_bandwidth, link_crypto);
        }

        accept;
    }

    reject;
}


################################################
#                 TATK Custom                  #
################################################

function ibgp_import_filter() {
    # Only process routes originating from BGP unless they're anycast networks
    if (source != RTS_BGP && !is_ibgp_network()) then {
        reject "ibgp_import_filter: rejecting unknown prefix", net;
    }

    if (bgp_path.len = 0) then {
        # Prefer locally originated iBGP routes, e.g. for anycast services
        bgp_med = 10;
    }

    accept;
}

function ibgp_export_filter() {
    if (source != RTS_BGP && !is_ibgp_network()) then {
        reject;
    }

    accept;
}

function ibgp_export_summary() {
    if (source ~ [RTS_STATIC, RTS_DEVICE]) then {
        if ((is_self_net() || is_self_net_v6()) && !is_self_net_aggregate()) then {
            reject;
        }

        accept;
    } else {
        reject;
    }
}

function ebgp_export_ownnets(int link_latency; int link_bandwidth; int link_crypto) {
     if (source ~ [RTS_STATIC, RTS_DEVICE]) then {
        bgp_community.add((64511, DN42_REGION));
        bgp_community.add((64511, DN42_COUNTRY));
    }

    if (is_ibgp_network()) then {
            update_flags(link_latency, link_bandwidth, link_crypto);
            accept;
    }

  reject;
}