protocol bgp dn42_21732  from dn42_peer {
    neighbor fe80::b8bd:45d2:9bf6:ee1d as 4242421732;
    interface "dn42-baragoon";

    ipv4 {
        import where dn42_import_filter(1,24,34);
        export where dn42_export_filter(1,24,34);
        extended next hop on;
    };

    ipv6 {
        import where dn42_import_filter(1,24,34);
        export where dn42_export_filter(1,24,34);
        extended next hop on;
    };
}

###
###

protocol bgp dn42_20566 from dn42_peer {
    neighbor fe80::566:11 as 4242420566;
    interface "dn42-cdubs";

    ipv4 {
        import where dn42_import_filter(2,24,34);
        export where dn42_export_filter(2,24,34);
        extended next hop on;
    };

    ipv6 {
        import where dn42_import_filter(2,24,34);
        export where dn42_export_filter(2,24,34);
        extended next hop on;
    };
}

###
###

protocol bgp client_home {
    local as 4242423152;
    neighbor 172.22.129.80 as 4242423152;
    source address 172.22.129.65;
    advertise hostname on;

    ipv4 {
        import where ibgp_import_filter();
        export where ibgp_export_summary();
        next hop address 172.22.129.65;
        next hop self ebgp;
        extended next hop on;
    };

    ipv6 {
        import where ibgp_import_filter();
        export where ibgp_export_summary();
        next hop address fdb2:e864:673e:3152::65;
        next hop self ebgp;
    };
}

###
###

protocol bgp dn42_23914 from dn42_peer {
    neighbor fe80::ade0 as 4242423914;
    interface "dn42-kioubit";

    ipv4 {
        import where dn42_import_filter(1,24,34);
        export where ebgp_export_ownnets(1,24,34);
        extended next hop on;
    };

    ipv6 {
        import where dn42_import_filter(1,24,34);
        export where ebgp_export_ownnets(1,24,34);
        extended next hop off;
    };
}

###
###

protocol bgp dn42_23035 from dn42_peer {
    neighbor fe80::3035:138 as 4242423035;
    interface "dn42-lare";

    ipv4 {
        import where dn42_import_filter(2,24,34);
        export where dn42_export_filter(2,24,34);
        extended next hop on;
    };

    ipv6 {
        import where dn42_import_filter(2,24,34);
        export where dn42_export_filter(2,24,34);
        extended next hop on;
    };
}

###
###

protocol bgp dn42_20207 from dn42_peer {
    neighbor fe80::207 as 4242420207;
    interface "dn42-routedbits";

    ipv4 {
        import where dn42_import_filter(1,24,34);
        export where dn42_export_filter(1,24,34);
        extended next hop on;
    };

    ipv6 {
        import where dn42_import_filter(1,24,34);
        export where dn42_export_filter(1,24,34);
        extended next hop on;
    };
}